config/routes.rb
DomPostroim::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => 'devise/registrations' }

  devise_scope :user do
    match 'new/:role' => 'devise/registrations#new', :as => 'sign_up'
  end

  match 'jobs/:job_id/bids/:id/accept' => 'bids#accept', :as => 'accept_bid'

  resources :users, :only => [:show]

  resources :jobs do
    resources :comments, :only => [:new, :create]
    resources :bids, :only => [:new, :create]
    resources :ratings, :only => [:new, :create, :index]
    match 'complete' => 'jobs#complete'
  end

  root :to => 'jobs#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    if user.role? :tradesman
      can :read, :all
      can :create_bid_for_job, Job
    end

    if user.role? :homeowner
      can :read, :all
      can :create, Job
      can :update, Job, :user_id => user.id
      can :destroy, Job, :user_id => user.id
      can :accept_bids, Job, :user_id => user.id
      can :complete, Job, :user_id => user.id
    end
    # Define abilities for the passed in user here. For example:
    #
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :job
  attr_accessible :comment, :cost, :user_id, :accepted
  scope :accepted, where(:accepted => true)
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :text, :user
  belongs_to :job
  belongs_to :user
  validates_presence_of :text
end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :name, :location, :description, :user_id, :accepted, :complete
  has_many :comments, :dependent => :delete_all
  has_many :bids, :dependent => :delete_all
  has_many :ratings
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :user
  belongs_to :job
  attr_accessible :comment, :evaluation, :job_id, :homeowner_id, :tradesman_id
  #validates :evaluation, :inclusion => EVALUATION, :message => "%{value} is not valid"

  EVALUATION = %w[like didnt_like]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  validates :role, :presence => true
  has_many :comments
  has_many :ratings, :dependent => :delete_all

  attr_accessor :login

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :login, :role
  # attr_accessible :title, :body

  def role?(role)
    self.role == role.to_s
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email = :value)", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bids_controller.rb
# encoding: UTF-8
class BidsController < ApplicationController
  before_filter :find_job
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to @job, :alert => 'Вы не можете этого сделать.'
  end

  def new
    authorize! :create_bid_for_job, @job
    @bid = @job.bids.build
  end

  def create
    authorize! :create_bid_for_job, @job
    @bid = @job.bids.build(params[:bid].try(:merge!, :user_id => current_user.id))
    if @bid.save
      flash[:notice] = 'Вы успешно откликнулись на заявку'
      redirect_to @job
    else
      flash[:alert] = 'Что-то пошло не так. Вы не откликнулись на заявку'
      redirect_to @job
    end
  end

  def accept
    authorize! :accept_bids, @job, :message => 'Вы не можете этого сделать.'
    @bid = @job.bids.find(params[:id])
    @bid.update_attributes(:accepted => true)
    @job.update_attributes(:accepted => true)
    flash[:notice] = 'Вы приняли предложение от подрядчика'
    redirect_to @job
  end


  private

  def find_job
    @job = Job.find(params[:job_id])
  end
end

app/controllers/comments_controller.rb
# encoding: UTF-8
class CommentsController < ApplicationController
  before_filter :find_a_job


  def new
    @comment = @job.comments.build
  end

  def create
    @comment = @job.comments.build(params[:comment].try(:merge!, :user => current_user))
    if @comment.save
      flash[:notice] = 'Вы задали вопрос.'
      redirect_to @job
    else
      flash[:alert] = 'Что-то пошло не так. Вопрос не был задан.'
      render 'new'
    end
  end

  private
  def find_a_job
    @job = Job.find(params[:job_id])
  end
end

app/controllers/jobs_controller.rb
# encoding: UTF-8
class JobsController < ApplicationController
  load_and_authorize_resource :only => [:new, :create, :edit, :destroy, :complete]
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to jobs_path, :alert => 'Вы не можете этого сделать.'
  end

  def index
    @jobs = Job.all
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(params[:job].merge!(:user_id => current_user.id))
    if @job.save
      flash[:notice] = "Работа создана."
      redirect_to @job
    else
      flash[:alert] = "Работа не создана."
      render :action => "new"
    end
  end

  def show
    @job = Job.find(params[:id])
    @bids = @job.bids.where('accepted' => true)
    @users = []
    @bids.each do |bid|
      @users << User.find_by_id(bid.user_id)
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update_attributes(params[:job])
      flash[:notice] = 'Вы успешно изменили свою заявку'
      redirect_to @job
    else
      flash[:alert] = 'Вы не изменили заявку'
      redirect_to @job
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    flash[:notice] = 'Вы удалили свою заявку'
    redirect_to jobs_path
  end

  def complete
    @job = Job.find(params[:job_id])
    #tradesman = 
    @job.update_attributes(:complete => true)
    flash[:notice] = 'Ваша работа завершена. Пожалуйста, оставьте отзыв о работе подрядчика.'
    redirect_to @job
  end
end

app/controllers/ratings_controller.rb
# encoding: UTF-8
class RatingsController < ApplicationController
  before_filter :find_a_job

  def new
    @rating = @job.ratings.build
  end

  def create
    @rating = @job.ratings.build
    @rating.update_attributes(:job_id => @job.id, :homeowner_id => current_user.id, :tradesman_id => params[:tradesman_id])
    if @rating.save
      flash[:notice] = "Вы оставили отзыв о работнике. Спасибо!"
      redirect_to @job
    else
      flash[:alert] = "Что-то пошло не так"
      redirect_to @job
    end
  end

  private

  def find_a_job
    @job = Job.find(params[:job_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/bids/_form.html.erb
<%= simple_form_for [@job, @bid] do |f| %>
  <%= f.input :cost, :label => 'Стоимость', :hint => 'Например от 5,000 до 7,000',
    :input_html => { :class => 'span8' } %>
    <%= f.input :comment, :label => 'Комментарий', :hint => 'Краткое пояснение такой цены',
      :input_html => { :class => 'span8' } %>
  <%= f.button :submit, 'Откликнуться', :class => 'btn-success' %>
<% end %>

app/views/bids/new.html.erb
<%= render 'form' %>

app/views/comments/_form.html.erb
<%= simple_form_for [@job, @comment] do |f| %>
  <%= f.input :text, :label => 'Вопрос', :as => :text,
      :input_html => { :class => 'span8' } %>
  <%= f.button :submit, 'Создать', :class => 'btn-success' %>
<% end %>

app/views/jobs/_bids.html.erb
<h2>Предложения от подрядчиков</h2>
<% @job.bids.each do |bid| %>
  <div class='span2'>
    <%= link_to User.find(bid.user_id).username, user_path(User.find(bid.user_id)) %> </br>
    Стоимость:</br>
    <ul>
      <li><%= bid.cost %></li>
    </ul>
  </div>
  <div class='span4'>
    <%= bid.comment %>
  </div>
  <div class='span4'>
    <%= link_to 'Принять', accept_bid_path(@job, bid), :method => :put, :class => 'btn-success' %>
  </div>
<% end %>

app/views/jobs/_comments.html.erb
<% @job.comments.each do |comment| %>
  <div><%= comment.text %></div>
<% end %>

app/views/jobs/_edit_form.html.erb
<%= simple_form_for @job do |f| %>
  <%= f.input :name, :label => 'Название',
    :input_html => { :class => 'span8' } %>
    <%= f.input :description, :label => 'Описание работ', :as => :text,
      :input_html => { :class => 'span8' } %>
  <%= f.input :location, :label => 'Город',
      :input_html => { :class => 'span8' } %>
  <%= f.button :submit, 'Изменить', :class => 'btn-success' %>
<% end %>

app/views/jobs/_form.html.erb
<%= simple_form_for @job do |f| %>
  <%= f.input :name, :label => 'Название', :hint => 'Например Покраска пола',
    :input_html => { :class => 'span8' } %>
    <%= f.input :description, :label => 'Описание работ', :as => :text,
      :input_html => { :class => 'span8' } %>
  <%= f.input :location, :label => 'Город',
      :input_html => { :class => 'span8' } %>
  <%= f.button :submit, 'Создать', :class => 'btn-success' %>
<% end %>

app/views/jobs/_ratings.html.erb
<% @users.each do |user| %>
  <%= link_to "Оставить отзыв для #{user.username}", new_job_rating_path(@job, :tradesman_id => user.id) %></br>
<% end %>

app/views/jobs/edit.html.erb
<h1>Изменить заявку</h1>
<%= render 'edit_form' %>

app/views/jobs/index.html.erb
<% @jobs.each do |job| %>
  <div class='row'>
    <div class='span8' style='border: 1px solid #08c'>
      <h3><%= link_to job.name, job_path(job) %></h3>
      <div class='row'>
        <div class='span4'>
          <address><%= job.location %></address>
        </div>
      </div>
      <%= job.description %>
    </div>
  </div>
<% end %>
<%= link_to 'Новая заявка', new_job_path, :id => 'новая заявка' %>

app/views/jobs/show.html.erb
<h2><%= @job.name %></h2>
<div><%= link_to 'Изменить', edit_job_path(@job) %></div>
<div><%= link_to 'Удалить', job_path(@job), :method => :delete, :data => { :confirm => 'Ваша заявка будет удалена. Продолжить?' }, 
        :class => 'btn-danger' %></div>
      <div><%= link_to 'Откликнуться', new_job_bid_path(@job), :class => 'btn-info' %></div>
      <div><%= link_to 'Работа завершена', job_complete_path(@job), :method => :put %></div>
      <div><%= render 'ratings' %>
<div class="row">
  <div class="span4">
    <strong>Город:</strong> <%= @job.location %>
  </div>
</div>
<div class="row">
  <div class="span8">
    <strong>Описание:</strong></br>
    <%= @job.description %>
  </div>
  <div class='span4'>
    <%= render 'bids' %>
  </div>
</div>
<div class='row'>
  <div class='span8'>
    <%= link_to 'Задать вопрос', new_job_comment_path(@job) %>
    <%= render 'comments' %>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class='navbar'>
  <div class='navbar-inner'>
    <div class='container'>
      <%= link_to 'Dom Postroim', root_path, :class => 'brand' %>
      <ul class='nav'>
        <% if user_signed_in? %>
          <li class='navbar-text nav pull-right'><%= current_user.username %></li>
          <li><%= link_to 'Выйти', destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to 'Зарегистрироваться как заказчик', sign_up_path(:role => 'homeowner') %></li>
          <li><%= link_to 'Зарегистрироваться как подрядчик', sign_up_path(:role => 'tradesman') %></li>
          <li><%= link_to 'Войти', new_user_session_path(current_user) %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DomPostroim</title>
  <%= stylesheet_link_tag    'application', :media => 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class='container header'>
    <%= render 'layouts/header' %>
  </div>
  <div class='container'>

    <% flash.each do |name, msg| %>
      <div class='alert alert-<%= name == :notice ? 'success' : 'error' %>'>
        <%= msg %>
      </div>
    <% end %>

    <%= yield %>
    <%= debug(params) %>
  </div>
</body>
</html>

app/views/ratings/_rating_form.html.erb
<%= simple_form_for [@job, @rating] do |f| %>
  <%= f.input :evaluation, :label => 'Оценка', :collection => [['like', 'Понравилось'], ['didnt_like', 'Не понравилось']], :label_method => :last, :value_method => :first, :as => :radio %>
  <% #f.input :evaluation, :label => 'Оценка', :as => :radio_buttons, :collection => Rating::EVALUATION, :value_method => ['Нра', 'Не нра'] %>
  <%= f.input :comment, :label => 'Ваш отзыв', :placeholder => 'Краткий комментарий ...' %>
  <%= f.submit 'Оставить отзыв' %>
<% end %>

app/views/ratings/new.html.erb
<%= render 'rating_form' %>